### PR TITLE
Remove unused gems

### PR DESCRIPTION
**Pull request by artur-beljajev**
We don't use them and they seem to be effectively abandoned.

Also, removing `autodoc` gem allows us to fully get rid of `rspec` dependency.

### CODE REVIEW

**Comment by artur-beljajev** [comment]
@vohmar Is there anything that prevents this from being merged?

**Comment by vohmar** [comment]
these gems are used for automatically updating / generating documentation

**Comment by teadur** [comment]
Seems to be related to #247

**Comment by yulgolem** [comment]
sdoc gem will be substituted for yard gem.

**Pull request merged**
