### PR TITLE
Make registrar address required

### PR DESCRIPTION
**Pull request by artur-beljajev**
Includes refactoring of registrar admin views:

- Reorganize views
- Improve database structure
- Use default translations
- Combine tests

### CODE REVIEW

**Comment by vohmar** [comment]
* url value is missing from view and pdf
* email value is on url line in pdf

**Comment by artur-beljajev** [comment]
Cannot reproduce http://prntscr.com/nmuwdo. There is no registrar PDF view in admin.

**Comment by vohmar** [comment]
the issue i not there in master as website is not present in invoice pdf in master

**Comment by artur-beljajev** [comment]
See https://github.com/internetee/registry/pull/1195#issuecomment-491313334. Anyway, I can't help if you don't post any screenshot.

**Comment by vohmar** [comment]
image

**Comment by artur-beljajev** [comment]
How is this connected to this PR?

**Comment by artur-beljajev** [comment]
Are you sure you can't reproduce it using `master` branch?

**Comment by vohmar** [comment]
problem resolved it self

**Comment by artur-beljajev** [comment]
Martin:

`select count(*) from registrars where street is null
select count(*) from registrars where zip is null
select count(*) from registrars where city is null
select count(*) from registrars where state is null`

There are no such records in production.

**Pull request merged**
