### PR TITLE
Change `contacts.name` to NOT NULL

### PR DESCRIPTION
**Pull request by artur-beljajev**
Check prod.

### CODE REVIEW

**Comment by vohmar** [comment]
cannot be done as there are empty name values already in production db

**Comment by artur-beljajev** [comment]
If it's absolutely necessary to leave that "broken" contacts there, we could change `NULL` to empty string. If our current policy states that we do require the name, the corresponding column must be declared as `NOT NULL`.

**Comment by maciej-szlosarczyk** [comment]
Alternatively we can also look at the history of these contacts, and see what was the registrar_id in the past, as it should be in Paperclip. And then contact that registrar to make the changes we need.

**Comment by vohmar** [comment]
blocked by https://github.com/internetee/registry/issues/956

**Comment by artur-beljajev** [comment]
#956 is fixed.

**Comment by vohmar** [comment]
blocked until contact archivation updates are in production and we can be sure there are no active contacts with missing name value left

**Pull request closed without merging**
