### PR TITLE
Change `invoices.issue_date` database column to `NOT NULL`

### LINKED ISSUE #1008: Change `invoices.issue_date` to NOT NULL
Couldn't be done in #1013 because of pending data migration.
Remove model validation.

### PR DESCRIPTION
**Pull request by artur-beljajev**
- Deploy _only_ once `populate_invoice_issue_date` data migration is run against every deployment, since this change removes it!
- _Cannot_ be released along with https://github.com/internetee/registry/pull/1013.

Closes #1008

### CODE REVIEW

**Comment by vohmar** [comment]
deployment failed on staging due to null issue_date values. All the issue_date columen values are empty for that matter so apparently populate_invoice_issue_date was not run

```
       rake aborted!
       StandardError: An error has occurred, this and all later migrations canceled:

       PG::NotNullViolation: ERROR:  column "issue_date" contains null values
       : ALTER TABLE "invoices" ALTER "issue_date" SET NOT NULL
```

**Comment by artur-beljajev** [comment]
Then run it!

**Comment by vohmar** [comment]
I cannot as db is replaced with every deployment so this migration should be run in the deployment process prior to removing it

**Comment by artur-beljajev** [comment]
Then talk to @ratM1n to switch to fixtures. I briefly explained him a point of them (test data we use for testing).

**Comment by vohmar** [comment]
not able to deploy

**Comment by artur-beljajev** [comment]
How can I help?

**Comment by artur-beljajev** [comment]
@ratM1n Confirmed it's now in working state.

**Pull request merged**
