### PR TITLE
Set session timeout to 5 years in development and staging environments

### PR DESCRIPTION
**Pull request by artur-beljajev**
- Needed to avoid signing in every 8 hours
- Nothing to test

### CODE REVIEW

**Comment by teadur** [comment]
Maybe we should have lower value for production then 8 hours. @ratM1n 
I think something smaller then 5 years for devel/staging would be "nicer".

**Comment by artur-beljajev** [comment]
Georg

> hour for prod, day for staging and 0 for dev

**Comment by artur-beljajev** [comment]
@ratM1n @teadur This is now configurable option
https://github.com/internetee/registry/pull/588/commits/030eaa3078bf8786ae8d13d1f165a63dbba563df#diff-318c31f2f8c28eecdbe0119432a98af0R131

**Comment by artur-beljajev** [comment]
Please make sure all envs are updated with the corresponding values. Session is not limited unless set in application.yml

**Comment by vohmar** [comment]
this is now deployed on staging @teadur please test this configurable feature.

**Pull request merged**
