### PR TITLE
Refactor registrars

### PR DESCRIPTION
**Pull request by artur-beljajev**
Includes
- Under-the-hood changes needed for #623
- UI improvements (default header, breadcrumbs)
- Add tests
- Allow registrar removal if not in use

Test
- Registrars page in admin area

### CODE REVIEW

**Comment by vohmar** [comment]
does not deploy

```
       PG::UniqueViolation: ERROR:  could not create unique index "unique_reg_no"
       DETAIL:  Key (reg_no)=() is duplicated.
       :       ALTER TABLE registrars ADD CONSTRAINT unique_name UNIQUE (name);
       ALTER TABLE registrars ADD CONSTRAINT unique_reg_no UNIQUE (reg_no);
       ALTER TABLE registrars ADD CONSTRAINT unique_reference_no UNIQUE (reference_no);
       ALTER TABLE registrars ADD CONSTRAINT unique_code UNIQUE (code);
```

there are empty values in reg_no field in both staging and production dbs

**Comment by artur-beljajev** [comment]
OK, so basically #754 strikes again. Let me think about some quick solution.

**Comment by artur-beljajev** [comment]
I checked it again, and actually #754 has nothing to do with the issue you specified. According to business logic, `registrars.reg_no`, cannot be blank (along with other attributes: https://github.com/internetee/registry/blob/a5869e0ecad1927b47d4e12188cc57508870029e/app/models/registrar.rb#L16)

**Comment by vohmar** [comment]
optional it is then

**Comment by artur-beljajev** [comment]
How about uniqueness check? Do need it?

**Comment by vohmar** [comment]
assuring that if value exists it is unique is nice to have feature

**Comment by artur-beljajev** [comment]
I need your assistance to solve the following problem:

This ticket has a migration which adds missing unique constraint to `registrars.reg_no` (it is required to be present and unique at the application level). The migration fails because of empty values in that column which are obviously not unique. I cannot use `NULL` since that column is declared as `NOT NULL`. So the only way to fix it is to fill with some value. Is it possible?


@virtualfeline, @teadur, @ratM1n

**Comment by virtualfeline** [comment]
Perhaps reg_no should not be unique at all. 

Consider that we have companies from different countries. It is conceivable that business registry numbers might coincide if 2 countries use similar format. 

Also we already had a real case in production when one registrar accredited, left, and came back again as different registrar while having the same company number. So we already do have 2 registrars in production that have the same reg_no value, not only NULLs. 

Also, what is the benefit of having this be unique? Doesn't seem useful in any way.

**Comment by artur-beljajev** [comment]
@virtualfeline No idea about benefit :) I just added a missing constraint (app validated its uniqueness before anyway). I think the problem I described disappears once we drop uniqueness requirement.

If @vohmar confirms it, I will do in in a separate ticket.

**Comment by vohmar** [comment]
blocked by #776

**Comment by artur-beljajev** [comment]
`reg_no` uniqueness validation and database constraint are now removed.

@ratM1n If there is some env where the migration in question has been already applied, you need to manually remove `registrars.unique_reg_no` constraint.

**Comment by vohmar** [comment]
registrar delete returns internal error - registrar with history
`VM104 admin-manifest-5a58585d5fc971be059d49e52316f411f64b18682bd28ea0d4c0c941dd7b7b05.js:4610 POST https://staging-adm.infra.tld.ee:444/admin/registrars/50 500 (Internal Server Error)`

**Comment by artur-beljajev** [comment]
Fixed

**Pull request merged**
