### PR TITLE
Move DomainUpdateConfirm to Interactor

### LINKED ISSUE #1760: Move DomainUpdateConfirmJob to interactor
Part of #1198

### PR DESCRIPTION
**Pull request by yulgolem**
Closes #1760

### CODE REVIEW

**Review by karlerikounapuu — APPROVED** [review]

**Comment by vohmar** [comment]
* rejecting change does not remove cancel the pending update - not using registrant for nor admin. 

Accepting change and expire works

**Comment by vohmar** [comment]
now getting new error: Validation failed: Epp errors {:code=>"2304", :msg=>"Object status prohibits operation"}
https://errbit.internet.ee/apps/5bcf2b35d9d1af5a21961be2/problems/5fc659c8d9d1af0c4676e3b5

domain has only these statuses set:

* inactive
* pendingUpdate

inactive should not affect anything and pendingUpdate is the status that should be removed

**Comment by yulgolem** [comment]
@vohmar That's totally OK, if domain got pendingUpdate we assume it's not transferrable.
So let's together check this step by step.

**Comment by yulgolem** [comment]
Should be fixed now.
Also added test - if domain got no nameservers and its statuses includes `inactive`, this status should not be rejected on update rejection, only `pendingUpdate`.

**Pull request merged**
