### PR TITLE
Remove unused "restful_whois_url" config key

### PR DESCRIPTION
**Pull request by artur-beljajev**
Merged with staging, but is absent in master.

### CODE REVIEW

**Comment by artur-beljajev** [comment]
@teadur @ratM1n Could you briefly check it?

**Comment by artur-beljajev** [comment]
Also, please ensure "restful_whois_url" config key is remove from application.yml on all envs, if present.

**Comment by teadur** [comment]
Check what exactly ? if Registry/Whois/Rest-whois  doesnot use this param i would say its safe to remove it, no external application depends on application.yml

**Comment by artur-beljajev** [comment]
Check that 
`"restful_whois_url" config key is removed from application.yml on all envs, if present.`

**Comment by artur-beljajev** [comment]
Unused key should not present in any env-specific config file

**Comment by teadur** [comment]
Merge it

**Pull request merged**
