### PR TITLE
Remove unused CRON tasks

### PR DESCRIPTION
**Pull request by artur-beljajev**
Nothing to test.
@ratM1n @teadur Make sure a call to `DomainCron.start_delete_period`, `destroy_with_message`, `delete_legal_doc_duplicates` are removed from CRON

### CODE REVIEW

**Comment by artur-beljajev** [comment]
@ratM1n @teadur

**Comment by teadur** [comment]
@artur is poll message for domain delete generated somewhere else then destroy_with_message ?

**Comment by artur-beljajev** [comment]
Yes, here https://github.com/internetee/registry/blob/de5f06fa89796e8958d7e883a2deac841ebc3602/app/jobs/domain_delete_job.rb#L11

**Comment by teadur** [comment]
Okey thank you, as of legaldoc duplicates are removed by external script made by @ratM1n i think this can be merged.

**Pull request merged**
