### PR TITLE
Remove monkey patches

### PR DESCRIPTION
**Pull request by artur-beljajev**
#231

### CODE REVIEW

**Comment by teadur** [comment]
Blocked by #231

**Comment by artur-beljajev** [comment]
I wonder what prevents this change from going live?

**Comment by teadur** [comment]
It's blocked by #594

**Comment by teadur** [comment]
Please restore the config/initializers/eis_custom_flash.rb
If user gets error internal, you cant search the logs via this keyword because nothing logs it now.

**Comment by artur-beljajev** [comment]
Why you want to log "flash error message"? Show me the problem!

**Comment by teadur** [comment]
I tried to login with MID, i got error internal on on client side, i tried to search for that keyword in logs, found nothing.
The problem is seen in log as:

Oct  4 14:24:30 staging REGISTRAR[28626]: [xxxx] [7dc7f886-8e3f-4e34-bd7a-3086f3ae4c3c] [x.x.x.x] Completed 400 Bad Request in 209m
s (Views: 0.6ms | ActiveRecord: 14.6ms)

**Comment by artur-beljajev** [comment]
Let's have proper bug report and handle it as a separate issue. Logging flash messages will not help in this case.

**Pull request merged**
