### PR TITLE
Improve EPP login

### LINKED ISSUE #1313: Authenticated EPP user is able to login repeatedly
https://github.com/internetee/registry/pull/1276#issuecomment-527764759

### PR DESCRIPTION
**Pull request by artur-beljajev**
@ratM1n or @teadur Notice new setting https://github.com/internetee/registry/pull/1314/files#diff-fc5026eef1f4752ef71315b36727e708R161

Fixes #1313, #587.

### CODE REVIEW

**Comment by vohmar** [comment]
#587 test failed - user is able to log in  unlimited number of times. Cannot find how to set the session limit (#543) - unable to test nor verify

**Comment by artur-beljajev** [comment]
> #587 test failed - user is able to log in unlimited number of times. Cannot find how to set the session limit (#543) - unable to test nor verify

Well, then it seems session limit per registrar never worked, since this PR only changes response code and does not touch any logic.

**Comment by artur-beljajev** [comment]
I need detailed description of how you test it.

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/issues/729

**Comment by vohmar** [comment]
#1313 is ok, second attempt to login in already auhtenitaed session resulted in error 2002 as expected.
#587 is still an issue - set the auth limit on application.yml to 4, sessions db table is clear, but user is still able to create more than 4 parallel sessions - in our test example 7 active sessions were created. To test, user form the same ip opens up multiple sessions directly to the epp interface (epptelnet)

**Comment by artur-beljajev** [comment]
See my previous comment.

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/pull/1331 should help.

**Comment by vohmar** [comment]
blocked by #1331

**Comment by yulgolem** [comment]
@ratM1n let's check this branch on staging.
Locally 5th login attempt goes 2502:Session limit exceeded; server closing connection (connection limit reached).

**Comment by ratM1n** [comment]
Did I miss something, but after adding `epp_sessions_per_registrar: '4'` to application.yml and restart, I'm getting on login:

`
    <result code="2502">
      <msg lang="en">Session limit exceeded; server closing connection (connection limit reached)</msg>
    </result>
`

**Comment by ratM1n** [comment]
OK! seems to work correctly and also ignore expired sessions if present in database.

**Pull request merged**
