### PR TITLE
Update outdated doc

### PR DESCRIPTION
**Pull request by artur-beljajev**

### CODE REVIEW

**Comment by vohmar** [comment]
instead of removing the doc it should be updated with information on how the setup and running of tests is done now.

**Comment by artur-beljajev** [comment]
It is run using default `bin/rake test` and `bin/rspec` commands. Are you sure it needs to be specified? Our project anyway assumes some familiarity with Rails basics, so I don't think we need to cover such topic in detail.

**Comment by artur-beljajev** [comment]
@vohmar Can we solve this problem comprehensively in a separate ticket? It makes no sense to update this doc in its current version. Nothing is helpful there.

**Comment by yulgolem** [comment]
Updated testing.md documentation file to reflect our current testing approach using docker images.

**Pull request merged**
