### PR TITLE
Registrant area cleanup

### PR DESCRIPTION
**Pull request by artur-beljajev**
Test:
- Registrant area UI for anomalies
- Links in confirmation emails

### CODE REVIEW

**Comment by vohmar** [comment]
@artur-beljajev confirmation accept does not work - pressing accept button in the accept/reject form does not close the pending update status. Reject works, but accept seems to do nothing - no error, success page is displayed to user, but pending status remains.

**Comment by artur-beljajev** [comment]
Confirmation of what? Registrant change?

**Comment by vohmar** [comment]
merge conflicts! the same issue is with #666 - reverted #692

**Comment by vohmar** [comment]
merge conflicts with master - cannot be automatically merged

**Comment by artur-beljajev** [comment]
Already merged

**Pull request closed without merging**
