### PR TITLE
bundle with 2x

### PR DESCRIPTION
**Pull request by teadur**
Closes https://github.com/internetee/registry/issues/1078.

### CODE REVIEW

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/issues/1078

**Comment by artur-beljajev** [comment]
Upgrade process is explained here in detail: https://github.com/internetee/registry/issues/1078#issue-405999019

**Comment by teadur** [comment]
@artur-beljajev
The build seems to work fine to me, i don't know why ruby 2.3 would be problem when we are already on 2.4x

**Comment by artur-beljajev** [comment]
@teadur Indeed, it seems I missed Ruby upgrade somehow 😕. So everything is OK.

One more thing: it's worth adding this line https://github.com/internetee/auction_center/blob/master/.travis.yml#L15 as well (as stated in Bundler upgrade doc).

**Pull request merged**
