### PR TITLE
Add `ActionVersion`

### PR DESCRIPTION
**Pull request by artur-beljajev**
Deleting a contact with actions should create both `contact` and `action` versions (`log_contacts` and `log_actions` respectively).

Needed for https://github.com/internetee/registry/pull/1146.

### CODE REVIEW

**Comment by vohmar** [comment]
no records are created in log_actions table on contact update in registrant portal - records are created/updated in action, contacts and log_contacts.

**Comment by vohmar** [comment]
epp contact:delete returns internal error if contact has records in actions tabel

**Comment by vohmar** [comment]
internal error is still returned upon an attempt to delete a contact with records in actions table

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/pull/1239#issue-290643863

**Pull request merged**
