### PR TITLE
Improve EPP poll tests

### PR DESCRIPTION
**Pull request by artur-beljajev**
Verify that EPP poll request returns the latest message.

### CODE REVIEW

**Comment by vohmar** [comment]
tests fail

**Comment by artur-beljajev** [comment]
See referenced ticket #948

**Comment by artur-beljajev** [comment]
NB! PR is updated and now requires some testing. See above for the details.

**Comment by vohmar** [comment]
merge conflict

**Comment by artur-beljajev** [comment]
Fixed

**Pull request merged**
